name = "DotEnv"
uuid = "4dc1fcf4-5e3b-5448-94ab-0c38ec0385c1"
authors = ["Valent√≠n Mari"]
version = "0.3.0"

[deps]

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
